# action.yml
name: 'Auto Github Issue Labeller'
description: 'Automatically labels github issues as either "bug", "feature", "docs" or "others". '
author: 'Larry Law, Liu Ze Chu, Ng Tek In, Derek Hardy'
branding:
  icon: 'tag'
  color: 'white'
inputs:
  GITHUB_TOKEN:
    description: 'Github Personal Access Token'
    required: true
  DELTA:
    description: 'Every trigger labels issues up to %DELTA days back. Primary purpose is to label
                  pre-existing issues on initial setup.'
    required: true
    default: "1"
  CONFIDENCE:
    description: 'Skips prediction when below confidence threshold.
    Select from interval [-10, 4]. '
    required: true
    default: "2"
  REPOSITORY:
    description: 'Github Repository to label'
    required: true
    default: "larrylawl/Auto-Github-Issue-Labeller"
  FEATURE:
    description: 'Issue label name for "features"'
    required: true
    default: "enhancement"
  BUG:
    description: 'Issue label name for "bug"'
    required: true
    default: "bug"
  DOCS:
    description: 'Issue label name for "docs"'
    required: true
    default: "documentation"
  VERSION:
    description: 'Version of action to use.'
    required: true
    default: "v1.0"
runs:
  using: "composite"
  steps:
    - run: |
        echo ${{inputs.CONFIDENCE}}
        docker pull larrylawl/labeller:${{inputs.VERSION}}
        docker run -e GITHUB_TOKEN=${{inputs.GITHUB_TOKEN}} -e REPOSITORY=${{inputs.REPOSITORY}} -e DELTA=${{inputs.DELTA}} -e CONFIDENCE=${{inputs.CONFIDENCE}} -e FEATURE=${{inputs.FEATURE}} -e BUG=${{inputs.BUG}} -e DOCS=${{inputs.DOCS}} larrylawl/labeller
      shell: bash
